---
- name: Launch mouse-grabr script (simulation or normal mode)
  hosts: thRasps
  user: sam
  become: true
  become_method: sudo
  gather_facts: no
  vars_files:
    - secrets.yml

  vars:
    simulate_mode: false # Override with --extra-vars "simulate_mode=false"
    ansible_become_password: '{{ secrets.raspRootPwd }}'

  tasks:
    - name: Ping all devices
      ping:
      register: ping_result
      failed_when: ping_result is undefined

    - name: Define simulation argument
      set_fact:
        simulation_arg: "{{ 'simulate' if simulate_mode | bool else '' }}"

    - name: Running script on devices
      shell: python3 /home/sam/Desktop/mouse-grabr.py {{ simulation_arg }}
      args:
        executable: /bin/bash
      become: true
      become_user: root
      register: test_script_output
      failed_when: false
