---
- name: Reboot responsive hosts
  hosts: thRasps
  user: sam
  gather_facts: no
  become: yes
  vars_files:
    - secrets.yml

  vars:
    ansible_become_password: '{{ secrets.raspRootPwd }}'

  tasks:
    - name: Ping all devices and mark responsive hosts
      ansible.builtin.ping:
      register: ping_result
      ignore_errors: yes # Allow playbook to continue if the ping fails

    # - name: Debug ping result
    #   ansible.builtin.debug:
    #     var: ping_result

    - name: Reboot responsive hosts
      ansible.builtin.shell: reboot
      when: ping_result is succeeded
      become: yes
      become_user: root
